version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: Fabrico2
      POSTGRES_PASSWORD: Fabrico2
      POSTGRES_DB: Fabrico2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
