"""User Table Update

Revision ID: 3296edd77dbf
Revises: 32bc0790efe4
Create Date: 2024-05-04 20:16:07.488869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3296edd77dbf'
down_revision = '32bc0790efe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userid', sa.String(length=120), nullable=True))
        batch_op.drop_index('ix_user_email')
        batch_op.create_index(batch_op.f('ix_user_userid'), ['userid'], unique=True)
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_userid'))
        batch_op.create_index('ix_user_email', ['email'], unique=True)
        batch_op.drop_column('userid')

    # ### end Alembic commands ###
