"""Add defectGray and defectBoundary columns to FabricDefects

Revision ID: 32bc0790efe4
Revises: 34111a9f742e
Create Date: 2024-05-03 19:47:02.371730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32bc0790efe4'
down_revision = '34111a9f742e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FabricDefects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('defectGray', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('defectBoundary', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FabricDefects', schema=None) as batch_op:
        batch_op.drop_column('defectBoundary')
        batch_op.drop_column('defectGray')

    # ### end Alembic commands ###
