"""updated relations4

Revision ID: 34111a9f742e
Revises: d279240c481e
Create Date: 2024-04-17 21:58:36.405913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34111a9f742e'
down_revision = 'd279240c481e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FabricDefects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('defect', sa.Text(), nullable=False))
        batch_op.create_foreign_key(None, 'defect', ['defect'], ['defect'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FabricDefects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('defect')

    # ### end Alembic commands ###
