"""Coordinates and meters column added

Revision ID: 7f7b7cbbe5d2
Revises: 3296edd77dbf
Create Date: 2024-05-05 18:41:43.262405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f7b7cbbe5d2'
down_revision = '3296edd77dbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FabricDefects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinates', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('meters', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FabricDefects', schema=None) as batch_op:
        batch_op.drop_column('meters')
        batch_op.drop_column('coordinates')

    # ### end Alembic commands ###
