"""userid foreign key Fabric table

Revision ID: 90a2b823689b
Revises: 7f7b7cbbe5d2
Create Date: 2024-05-05 20:26:55.435167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90a2b823689b'
down_revision = '7f7b7cbbe5d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fabric', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userid', sa.String(length=120), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['userid'], ['userid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fabric', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('userid')

    # ### end Alembic commands ###
