"""Admin Portal

Revision ID: c1f0ebe61b7c
Revises: 90a2b823689b
Create Date: 2024-05-06 05:33:01.502743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f0ebe61b7c'
down_revision = '90a2b823689b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('userid', sa.String(length=256), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('fabric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fabric_id', sa.Text(), nullable=True),
    sa.Column('total_defects', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('userid', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fabric_id')
    )
    op.create_table('FabricDefects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('defect', sa.Text(), nullable=False),
    sa.Column('fabric_id', sa.Text(), nullable=False),
    sa.Column('defectimage', sa.LargeBinary(), nullable=True),
    sa.Column('defectGray', sa.LargeBinary(), nullable=True),
    sa.Column('defectBoundary', sa.LargeBinary(), nullable=True),
    sa.Column('coordinates', sa.Text(), nullable=True),
    sa.Column('meters', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['defect'], ['defect.defect'], ),
    sa.ForeignKeyConstraint(['fabric_id'], ['fabric.fabric_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FabricDefects')
    op.drop_table('fabric')
    op.drop_table('user')
    # ### end Alembic commands ###
