"""updated relations

Revision ID: d279240c481e
Revises: fb791e09e3dc
Create Date: 2024-04-17 21:45:30.954287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd279240c481e'
down_revision = 'fb791e09e3dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FabricDefects', schema=None) as batch_op:
        batch_op.drop_constraint('FabricDefects_defect_fkey', type_='foreignkey')
        batch_op.drop_column('defect')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FabricDefects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('defect', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('FabricDefects_defect_fkey', 'defect', ['defect'], ['defect'])

    # ### end Alembic commands ###
