"""Initial migration

Revision ID: fb791e09e3dc
Revises: 
Create Date: 2024-04-17 21:03:51.893271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb791e09e3dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FabricDefects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('defect', sa.Text(), nullable=False))
        batch_op.drop_constraint('FabricDefects_defect_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'defect', ['defect'], ['defect'])
        batch_op.drop_column('defect_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FabricDefects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('defect_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FabricDefects_defect_id_fkey', 'defect', ['defect_id'], ['id'])
        batch_op.drop_column('defect')

    # ### end Alembic commands ###
